test:
  image: elixir:1.7
  services:
  - postgres:latest
  variables:
    BRAVERA_DB_HOST: "postgres"
    MIX_ENV: "test"
  script:
  - mix do local.hex --force, local.rebar --force, deps.get --only test
  - mix test --exclude skip

production:
  stage: deploy
  environment: production
  image: docker:git
  only:
  - master
  script:
  - apk add --no-cache curl
  - L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
  - flynn cluster add -p $FLYNN_TLS_PIN $FLYNN_CLUSTER_NAME $FLYNN_CONTROLLER_URL $FLYNN_CONTROLLER_KEY --git-url=$FLYNN_GIT_URL
  - flynn -a bravera-staging remote add flynn
  - git checkout master
  - git push flynn master
  - flynn run mix ecto.migrate