test:
  image: plangora/alpine-elixir-phoenix:otp-23.3.2-elixir-1.11.3
  services:
  - postgis/postgis:13-master
  variables:
    MIX_ENV: "test"
    DB_HOST: postgis-postgis
    POSTGRES_DB: omega_bravera_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  script:
    - mix clean
    - mix do deps.get, test --exclude skip

include:
  - template: Jobs/Deploy.gitlab-ci.yml

staging_deploy:
  stage: deploy
  environment:
    name: staging
#    url: https://staging.bravera.co/
  extends: staging
  only:
    - feature/updateForContainer

production:
  stage: deploy
  environment: production
  image: plangora/alpine-elixir-phoenix:otp-23.3.2-elixir-1.11.3
  variables:
    MIX_ENV: "dev"
    REFSPEC: master
  only:
  - master
  before_script:
    - apk add --no-cache openssh-client procps
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p /root/.ssh
    - cp .deliver/ssh_config /root/.ssh/config
    - chmod -R 700 /root/.ssh
    - mix do deps.get, deps.compile
    - git branch -f master HEAD
  script:
    - mix edeliver update production -P --start-deploy
    - mix edeliver migrate production -P
    - mix edeliver ping production -P