image: elixir:1.6

services:
  - postgres:9.6

variables:
  BRAVERA_DB_HOST: "postgres"
  MIX_ENV: "test"

before_script:
  - apt-get update
  - apt-get install -y postgresql-client
  - mix do local.hex --force, local.rebar --force, deps.get --only test
  - mix do ecto.drop, ecto.create, ecto.load, ecto.migrate

test:
  script:
    - mix test