cache:
  key: bravera
  paths:
    - deps/
    - _build/

test:
  image: bitwalker/alpine-elixir-phoenix:latest
  services:
  - postgres:latest
  variables:
    MIX_ENV: "test"
  script:
  - mix do deps.get
  - mix test --exclude skip

docker_build:
  stage: build
  environment: staging
  only:
    - staging
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
    - docker:dind
  before_script:
    - docker info
  script:
      - docker build -t bravera --build-arg APP_BASE_URL --build-arg APP_HOST --build-arg AWS_ACCESS_KEY_ID --build-arg DATABASE_URL --build-arg ENABLE_EMAILS --build-arg ENABLE_MANUAL_ACTIVITIES --build-arg GOOGLE_ANALYTICS_ID --build-arg GUARDIAN_SECRET_KEY --build-arg S3_BUCKET_NAME --build-arg SECRET_KEY_BASE  --build-arg SENDGRID_API_KEY --build-arg STRAVA_ACCESS_TOKEN --build-arg STRAVA_CLIENT_ID --build-arg STRAVA_CLIENT_SECRET --build-arg STRAVA_REDIRECT_URI --build-arg STRIPE_PUBLIC_KEY --build-arg STRIPE_SECRET_KEY .

staging:
  stage: deploy
  environment: staging
  image: docker:git
  only:
  - staging
  script:
  - apk add --no-cache curl
  - L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
  - flynn cluster add -p $FLYNN_TLS_PIN $FLYNN_CLUSTER_NAME $FLYNN_CONTROLLER_URL $FLYNN_CONTROLLER_KEY --git-url=$FLYNN_GIT_URL
  - flynn -a bravera-staging remote add flynn
  - git checkout staging
  - git push flynn staging:master


production:
  stage: deploy
  environment: production
  image: docker:git
  only:
  - master
  script:
  - apk add --no-cache curl
  - L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
  - flynn cluster add -p $FLYNN_TLS_PIN $FLYNN_CLUSTER_NAME $FLYNN_CONTROLLER_URL $FLYNN_CONTROLLER_KEY --git-url=$FLYNN_GIT_URL
  - flynn -a bravera remote add flynn
  - git checkout master
  - git push flynn master
  - flynn run mix ecto.migrate