import Config

# Guardian config

config :omega_bravera, OmegaBravera.Guardian,
  issuer: "omega_bravera",
  secret_key: "TVCFw5ZzCC5gqI8FeRUg3jT7U578dbb4gGjBXq8Zt1Rk4ctVFj/zTRn6gfGOXiU0"

# Strava dev config
config :strava,
  client_id: "23267",
  client_secret: "508d46fce35e03a657546bf62283543c9ffe330f",
  access_token: "8830cb6e827146658aa034027d8d399ef1267b46",
  redirect_uri: "http://localhost:4000/strava/callback"

# Stripy dev config

config :stripy,
  secret_key: "sk_test_xgwHvfr4GBgJ9wrUDHoa1E57",
  endpoint: "https://api.stripe.com/v1/"

config :omega_bravera, :stripe_public_key, "pk_test_RM9ht2ztt3dMgpvjPAtpHOx6"

# Guardian config

config :omega_bravera, OmegaBravera.Guardian,
  issuer: "bravera",
  secret_key: "TVCFw5ZzCC5gqI8FeRUg3jT7U578dbb4gGjBXq8Zt1Rk4ctVFj/zTRn6gfGOXiU0"

# Email config
config :sendgrid,
  api_key: "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",
  sandbox_enable: true

# S3 bucket
# Have to set these because ExAws does not support adding defaults.
# For examble: secret_access_key: [{:system, "2zCdtR7An6okd6mwDbizUHdo1/zZQtXkN+foHYW5"}, :instance_role]
# is not supported and will complain the variable is not a string.
System.put_env("AWS_ACCESS_KEY_ID", "AKIAJQUCEKCP2T5JG2WA")
System.put_env("AWS_SECRET_ACCESS_KEY", "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")

config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "ap-southeast-1"

config :omega_bravera,
  images_bucket_name: "bravera-staging-images",
  images_cdn_url: "https://bravera-staging-images.s3.amazonaws.com"

config :ex_aws, :hackney_opts,
  follow_redirect: true,
  recv_timeout: 30_000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :omega_bravera, OmegaBraveraWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :omega_bravera, OmegaBraveraWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/omega_bravera_web/views/.*(ex)$},
      ~r{lib/omega_bravera_web/templates/.*(eex)$},
      ~r{lib/omega_bravera_web/live/.*(ex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

config :absinthe,
  log: true

config :absinthe, Absinthe.Logger, pipeline: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :omega_bravera, OmegaBravera.Repo,
  username: "postgres",
  password: "postgres",
  database: "omega_bravera_dev",
  hostname: "localhost",
  pool_size: 10

# Manual activities
config :omega_bravera,
       :enable_manual_activities,
       not is_nil(System.get_env("ENABLE_MANUAL_ACTIVITIES"))

# Mobile App Links Setup
config :omega_bravera,
  app_links_verification: [
    apple: [
      appID: "CULKVWK3RD.co.bravera.braveraMobileApp"
    ],
    google: [
      namespace: "bravera_namespace",
      package_name: "co.bravera.bravera_mobile_app",
      sha256_cert_fingerprints: [
        # Sherief
        "3F:64:3B:A2:A8:E2:5E:CE:61:BC:69:C1:34:A7:5E:2C:EA:3B:FD:98:87:73:8F:A7:83:EB:93:69:91:5F:B7:D1",
        # Allen
        "45:38:9F:CC:BB:DC:D5:1E:9A:80:4E:BF:C2:97:25:57:F8:8B:82:9B:16:9D:86:DF:BC:F9:6B:99:7D:FB:D6:9F",
        # Release
        "DF:6E:65:4C:59:CD:2A:01:83:62:05:7D:CE:40:47:A0:09:EC:5D:32:73:19:37:58:8D:90:75:76:DA:36:D5:86"
      ]
    ]
  ]
