use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# OmegaBraveraWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :omega_bravera, OmegaBraveraWeb.Endpoint,
  http: [port: 4000],
  url: [host: "...", port: 80],
  cache_static_manifest: "priv/static/manifest.json",
  server: true,
  code_reloader: false

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :omega_bravera, OmegaBraveraWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :omega_bravera, OmegaBraveraWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
# TODO do I need this for AWS?
config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :omega_bravera, OmegaBraveraWeb.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"

config :omega_bravera, OmegaBraveraWeb.Endpoint,
  secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE")

config :omega_bravera, OmegaBravera.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: 20

# Strava dev config

config :strava,
  client_id: System.get_env("STRAVA_CLIENT_ID"),
  client_secret: System.get_env("STRAVA_CLIENT_SECRET"),
  access_token: System.get_env("STRAVA_ACCESS_TOKEN"),
  redirect_uri: System.get_env("STRAVA_REDIRECT_URI")

# Stripy dev config

config :stripy,
  secret_key: System.get_env("STRIPE_SECRET_KEY"),
  endpoint: "https://api.stripe.com/v1/"

config :omega_bravera, :stripe_public_key, System.get_env("STRIPE_PUBLIC_KEY")

# Guardian config
config :omega_bravera, OmegaBravera.Guardian,
  issuer: "bravera",
  secret_key: System.get_env("GUARDIAN_SECRET_KEY")

# Email config

config :omega_bravera, OmegaBravera.Mailer,
  adapter: Bamboo.SendgridAdapter,
  api_key: System.get_env("SENDGRID_API_KEY")

config :sendgrid,
  api_key: System.get_env("SENDGRID_API_KEY")
